import type { Race, ClassInfo, SkillInfo, Character, Armor, Shield, Background } from '../types';

export const SHIELD: Shield = {
  id: 'shield',
  name: 'Щит',
  bonus: 2,
  description: 'Деревянный/металлический щит. +2 к КД. Занимает одну руку.',
  cost: { gp: 10 },
  weight: 6,
};

export const ARMORS: Armor[] = [
  {
    id: 'none',
    name: 'Без брони',
    kind: 'none',
    baseAC: 10,
    dexCap: null,
    description: 'Естественная защита персонажа. КД = 10 + модификатор Ловкости.',
    cost: {},
    weight: 0,
  },
  {
    id: 'padded',
    name: 'Стёганка',
    kind: 'light',
    baseAC: 11,
    dexCap: null,
    description: 'Лёгкая броня из стёганой ткани. КД = 11 + мод. Ловкости.',
    cost: { gp: 5 },
    weight: 8,
    stealthDisadvantage: true,
  },
  {
    id: 'leather',
    name: 'Кожаная',
    kind: 'light',
    baseAC: 11,
    dexCap: null,
    description: 'Лёгкая кожа, плотно подогнанная. КД = 11 + мод. Ловкости.',
    cost: { gp: 10 },
    weight: 10,
  },
  {
    id: 'studded_leather',
    name: 'Заклёпанная кожа',
    kind: 'light',
    baseAC: 12,
    dexCap: null,
    description: 'Лучшая лёгкая броня с металлическими заклёпками. КД = 12 + мод. Ловкости.',
    cost: { gp: 45 },
    weight: 13,
  },
  {
    id: 'hide',
    name: 'Звериная',
    kind: 'medium',
    baseAC: 12,
    dexCap: 2,
    description: 'Толстая шкура. КД = 12 + мод. Ловкости (макс. +2).',
    cost: { gp: 10 },
    weight: 12,
  },
  {
    id: 'chain_shirt',
    name: 'Кольчужная рубаха',
    kind: 'medium',
    baseAC: 13,
    dexCap: 2,
    description: 'Кольчуга до бёдер. КД = 13 + мод. Ловкости (макс. +2).',
    cost: { gp: 50 },
    weight: 20,
  },
  {
    id: 'scale_mail',
    name: 'Чешуйчатая',
    kind: 'medium',
    baseAC: 14,
    dexCap: 2,
    description: 'Перекрывающиеся металлические пластины. КД = 14 + мод. Ловкости (макс. +2). Помеха Stealth.',
    cost: { gp: 50 },
    weight: 45,
    strengthRequired: 13,
    stealthDisadvantage: true,
  },
  {
    id: 'breastplate',
    name: 'Нагрудник',
    kind: 'medium',
    baseAC: 14,
    dexCap: 2,
    description: 'Металлический нагрудник. КД = 14 + мод. Ловкости (макс. +2).',
    cost: { gp: 400 },
    weight: 20,
  },
  {
    id: 'half_plate',
    name: 'Полулаты',
    kind: 'medium',
    baseAC: 15,
    dexCap: 2,
    description: 'Лучшая средняя броня. КД = 15 + мод. Ловкости (макс. +2). Помеха Stealth.',
    cost: { gp: 750 },
    weight: 40,
    strengthRequired: 13,
    stealthDisadvantage: true,
  },
  {
    id: 'ring_mail',
    name: 'Кольчужное облачение',
    kind: 'heavy',
    baseAC: 14,
    dexCap: 0,
    description: 'Тяжёлая броня. КД = 14 (мод. Ловкости не применяется). Помеха Stealth.',
    cost: { gp: 30 },
    weight: 40,
    stealthDisadvantage: true,
  },
  {
    id: 'chain_mail',
    name: 'Кольчуга',
    kind: 'heavy',
    baseAC: 16,
    dexCap: 0,
    description: 'Полные кольца от шеи до бёдер. КД = 16. Помеха Stealth. Требует СИЛ 13.',
    cost: { gp: 75 },
    weight: 55,
    strengthRequired: 13,
    stealthDisadvantage: true,
  },
  {
    id: 'splint',
    name: 'Полосовая',
    kind: 'heavy',
    baseAC: 17,
    dexCap: 0,
    description: 'Вертикальные полосы на кожаной основе. КД = 17. Помеха Stealth. Требует СИЛ 15.',
    cost: { gp: 200 },
    weight: 60,
    strengthRequired: 15,
    stealthDisadvantage: true,
  },
  {
    id: 'plate',
    name: 'Латы',
    kind: 'heavy',
    baseAC: 18,
    dexCap: 0,
    description: 'Цельнометаллический доспех. КД = 18. Помеха Stealth. Требует СИЛ 15.',
    cost: { gp: 1500 },
    weight: 65,
    strengthRequired: 15,
    stealthDisadvantage: true,
  },
];

export const CHARACTER_CLASSES: Record<string, ClassInfo> = {
  fighter: {
    id: 'fighter', name: 'Воин', description: 'Мастер боевых искусств и оружия.',
    hitDie: 10, primaryStat: 'STR',
    savingThrows: ['STR', 'CON'],
    skillPool: ['acrobatics', 'animal_handling', 'athletics', 'history', 'insight', 'intimidation', 'perception', 'survival'],
    skillChoices: 2,
    armorProficiencies: ['Лёгкая', 'Средняя', 'Тяжёлая', 'Щит'], weaponProficiencies: ['Простое', 'Военное'],
    featuresByLevel: {
      1: ['Боевой стиль', 'Второе дыхание'],
      2: ['Действие рывком'],
      3: ['Архетип бойца'],
      4: ['Улучшение характеристики'],
      5: ['Дополнительная атака'],
      6: ['Улучшение характеристики'],
      7: ['Объёмное размышление'],
      8: ['Улучшение характеристики'],
      9: ['Несокрушимость'],
      10: ['Дополнительный боевой стиль'],
      11: ['Дополнительная атака (2)'],
      12: ['Улучшение характеристики'],
      13: ['Углублённое объёмное размышление'],
      14: ['Улучшение характеристики'],
      15: ['Дополнительная атака (3)'],
      16: ['Улучшение характеристики'],
      17: ['Действие буйство'],
      18: ['Углублённое объёмное размышление'],
      19: ['Улучшение характеристики'],
      20: ['Дополнительное второе дыхание'],
    },
    spellcaster: 'none',
    subClasses: ['Мастер боевых искусств', 'Защитник', 'Чемпион', 'Покровитель боевых искусств'],
  },
  wizard: {
    id: 'wizard', name: 'Волшебник', description: 'Заклинатель тайной магии.',
    hitDie: 6, primaryStat: 'INT',
    savingThrows: ['INT', 'WIS'],
    skillPool: ['arcana', 'history', 'investigation', 'medicine', 'religion'],
    skillChoices: 2,
    armorProficiencies: [], weaponProficiencies: ['Кинжалы', 'Дартс', 'Праща', 'Боевые посохи', 'Лёгкие арбалеты'],
    featuresByLevel: {
      1: ['Наложение заклинаний', 'Арканное восстановление'],
      2: ['Тайная традиция'],
      3: ['Архетип волшебника'],
      4: ['Улучшение характеристики'],
      5: ['Арканное восстановление (2)'],
      6: ['Улучшение характеристики'],
      7: ['Тайная традиция (2)'],
      8: ['Улучшение характеристики'],
      9: ['Тайная традиция (3)'],
      10: ['Улучшение характеристики'],
      11: ['Тайная традиция (4)'],
      12: ['Улучшение характеристики'],
      13: ['Тайная традиция (5)'],
      14: ['Улучшение характеристики'],
      15: ['Тайная традиция (6)'],
      16: ['Улучшение характеристики'],
      17: ['Тайная традиция (7)'],
      18: ['Способности тайной традиции'],
      19: ['Улучшение характеристики'],
      20: ['Подписание чар'],
    },
    spellcaster: 'full',
    spellSlots: [{ level: 1, used: 0, total: 2 }],
    subClasses: ['Школа Прорицания', 'Школа Преобразования', 'Школа Ворожбы', 'Школа Иллюзии', 'Школа Вызывания', 'Школа Некромантии', 'Школа Отречения'],
  },
  rogue: {
    id: 'rogue', name: 'Плут', description: 'Хитрый мастер скрытности и ловкости.',
    hitDie: 8, primaryStat: 'DEX',
    savingThrows: ['DEX', 'INT'],
    skillPool: ['acrobatics', 'athletics', 'deception', 'insight', 'intimidation', 'investigation', 'perception', 'performance', 'persuasion', 'sleight_of_hand', 'stealth'],
    skillChoices: 4,
    armorProficiencies: ['Лёгкая'], weaponProficiencies: ['Простое', 'Ручные арбалеты'],
    featuresByLevel: {
      1: ['Коварная атака', 'Скрытая атака', 'Воровской жаргон'],
      2: ['Хитрое действие'],
      3: ['Архетип плута'],
      4: ['Улучшение характеристики'],
      5: ['Ускользание'],
      6: ['Улучшение характеристики'],
      7: ['Злонравие'],
      8: ['Улучшение характеристики'],
      9: ['Проницательность противника'],
      10: ['Улучшение характеристики', 'Хитрое действие (2)'],
      11: ['Надёжный талант'],
      12: ['Улучшение характеристики'],
      13: ['Проницательность противника (2)'],
      14: ['Улучшение характеристики'],
      15: ['Ускользание (2)'],
      16: ['Улучшение характеристики'],
      17: ['Проницательность противника (3)'],
      18: ['Невидимость'],
      19: ['Улучшение характеристики'],
      20: ['Поражающий удар'],
    },
    spellcaster: 'none',
    subClasses: ['Арканный фокусник', 'Убийца', 'Вор', 'Изгой-следопыт', 'Казначей фантазий', 'Мастер дуэлей', 'Инквизитив', 'Мастер фантазий'],
  },
  cleric: {
    id: 'cleric', name: 'Жрец', description: 'Слуга богов, владеющий божественной магией.',
    hitDie: 8, primaryStat: 'WIS',
    savingThrows: ['WIS', 'CHA'],
    skillPool: ['history', 'insight', 'medicine', 'persuasion', 'religion'],
    skillChoices: 2,
    armorProficiencies: ['Лёгкая', 'Средняя', 'Щит'], weaponProficiencies: ['Простое'],
    featuresByLevel: {
      1: ['Наложение заклинаний', 'Божественная воля', 'Изгнание нежити'],
      2: ['Божественный дом'],
      3: ['Архетип жреца'],
      4: ['Улучшение характеристики'],
      5: ['Уничтожение нежити (CR 1/2)'],
      6: ['Улучшение характеристики', 'Божественный дом (2)'],
      7: ['Уничтожение нежити (CR 1)'],
      8: ['Улучшение характеристики', 'Божественный аналог'],
      9: ['Уничтожение нежити (CR 2)'],
      10: ['Улучшение характеристики', 'Божественное вмешательство'],
      11: ['Уничтожение нежити (CR 3)'],
      12: ['Улучшение характеристики'],
      13: ['Уничтожение нежити (CR 4)'],
      14: ['Улучшение характеристики'],
      15: ['Уничтожение нежити (CR 5)'],
      16: ['Улучшение характеристики'],
      17: ['Уничтожение нежити (CR 6)'],
      18: ['Канал божества (2)'],
      19: ['Улучшение характеристики'],
      20: ['Улучшение божественного вмешательства'],
    },
    spellcaster: 'full',
    spellSlots: [{ level: 1, used: 0, total: 2 }],
    subClasses: ['Дом Знания', 'Дом Жизни', 'Дом Света', 'Дом Природы', 'Дом Бури', 'Дом Обмана', 'Дом Войны'],
  },
  barbarian: {
    id: 'barbarian', name: 'Варвар', description: 'Свирепый воин, черпающий силу в первобытной ярости.',
    hitDie: 12, primaryStat: 'STR',
    savingThrows: ['STR', 'CON'],
    skillPool: ['animal_handling', 'athletics', 'intimidation', 'nature', 'perception', 'survival'],
    skillChoices: 2,
    armorProficiencies: ['Лёгкая', 'Средняя', 'Щит'], weaponProficiencies: ['Простое', 'Военное'],
    featuresByLevel: {
      1: ['Ярость', 'Защита без доспехов'],
      2: ['Опасное чутьё', 'Безрассудная атака'],
      3: ['Путь варвара'],
      4: ['Улучшение характеристики'],
      5: ['Дополнительная атака', 'Быстрое движение'],
      6: ['Путь варвара (2)'],
      7: ['Инстинкт ярости', 'Феноменальная стойкость'],
      8: ['Улучшение характеристики'],
      9: ['Защита от brutal'],
      10: ['Путь варвара (3)'],
      11: ['Упорная ярость'],
      12: ['Улучшение характеристики'],
      13: ['Жестокий критический удар'],
      14: ['Улучшение характеристики', 'Путь варвара (4)'],
      15: ['Упорное неистовство'],
      16: ['Улучшение характеристики'],
      17: ['Ярость (5)'],
      18: ['Непреодолимая сила'],
      19: ['Улучшение характеристики'],
      20: ['Первобытный чемпион'],
    },
    spellcaster: 'none',
    subClasses: ['Путь Берсерка', 'Путь Тотемного Воина', 'Путь Бури', 'Путь Зверя', 'Путь Дзен-Лучника', 'Путь Кровавой Ярости'],
  },
  bard: {
    id: 'bard', name: 'Бард', description: 'Вдохновитель и заклинатель, использующий магию музыки и слова.',
    hitDie: 8, primaryStat: 'CHA',
    savingThrows: ['DEX', 'CHA'],
    skillPool: ['acrobatics', 'animal_handling', 'arcana', 'athletics', 'deception', 'history', 'insight', 'intimidation', 'investigation', 'medicine', 'nature', 'perception', 'performance', 'persuasion', 'religion', 'sleight_of_hand', 'stealth', 'survival'],
    skillChoices: 3,
    armorProficiencies: ['Лёгкая'], weaponProficiencies: ['Простое', 'Ручные арбалеты', 'Длинные мечи', 'Рапиры', 'Короткие мечи'],
    featuresByLevel: {
      1: ['Наложение заклинаний', 'Бардовые знания', 'Вдохновение барда'],
      2: ['Универсальное выступление', 'Песнь отдохновения'],
      3: ['Коллегия барда', 'Экспертиза'],
      4: ['Улучшение характеристики'],
      5: ['Вдохновение барда (2)', 'Волшебное восстановление'],
      6: ['Улучшение характеристики', 'Противословие'],
      7: ['Экспертиза (2)'],
      8: ['Улучшение характеристики'],
      9: ['Вдохновение барда (3)'],
      10: ['Улучшение характеристики', 'Магические секреты'],
      11: ['Завораживающее выступление'],
      12: ['Улучшение характеристики'],
      13: ['Вдохновение барда (4)'],
      14: ['Улучшение характеристики', 'Противословие (2)', 'Магические секреты (2)'],
      15: ['Вдохновение барда (5)'],
      16: ['Улучшение характеристики'],
      17: ['Вдохновение барда (6)'],
      18: ['Магические секреты (3)'],
      19: ['Улучшение характеристики'],
      20: ['Превосходное вдохновение'],
    },
    spellcaster: 'full',
    spellSlots: [{ level: 1, used: 0, total: 2 }],
    subClasses: ['Коллегия Знаний', 'Коллегия Доблести', 'Коллегия Отваги', 'Коллегия Шёпотов', 'Коллегия Гламура', 'Коллегия Мечей', 'Коллегия Сатиров'],
  },
  druid: {
    id: 'druid', name: 'Друид', description: 'Жрец природы, владеющий стихийной магией и диким обликом.',
    hitDie: 8, primaryStat: 'WIS',
    savingThrows: ['INT', 'WIS'],
    skillPool: ['arcana', 'animal_handling', 'insight', 'medicine', 'nature', 'perception', 'religion', 'survival'],
    skillChoices: 2,
    armorProficiencies: ['Лёгкая', 'Средняя (неметаллическая)', 'Щит (неметаллический)'], weaponProficiencies: ['Дубинки', 'Кинжалы', 'Дартс', 'Праща', 'Боевые посохи', 'Метательные дротики', 'Лёгкие арбалеты'],
    featuresByLevel: {
      1: ['Друидик', 'Наложение заклинаний'],
      2: ['Дикий облик', 'Круг друидов'],
      3: ['Архетип друида'],
      4: ['Улучшение характеристики', 'Дикий облик (2)'],
      5: ['Наложение заклинаний (2)'],
      6: ['Улучшение характеристики', 'Круг друидов (2)'],
      7: ['Архетип друида (2)'],
      8: ['Улучшение характеристики', 'Дикий облик (3)'],
      9: ['Наложение заклинаний (3)'],
      10: ['Улучшение характеристики', 'Круг друидов (3)'],
      11: ['Архетип друида (3)'],
      12: ['Улучшение характеристики'],
      13: ['Наложение заклинаний (4)'],
      14: ['Улучшение характеристики', 'Круг друидов (4)'],
      15: ['Архетип друида (4)'],
      16: ['Улучшение характеристики'],
      17: ['Наложение заклинаний (5)'],
      18: ['Без времени и не старея', 'Звериные заклинания'],
      19: ['Улучшение характеристики'],
      20: ['Архидруид'],
    },
    spellcaster: 'full',
    spellSlots: [{ level: 1, used: 0, total: 2 }],
    subClasses: ['Круг Земли', 'Круг Луны', 'Круг Паствы', 'Круг Шпор', 'Круг Сновидений', 'Круг Мороза'],
  },
  artificer: {
    id: 'artificer', name: 'Изобретатель', description: 'Мастер магии и механики, создающий магические изобретения.',
    hitDie: 8, primaryStat: 'INT',
    savingThrows: ['INT', 'CON'],
    skillPool: ['arcana', 'history', 'investigation', 'medicine', 'perception', 'sleight_of_hand'],
    skillChoices: 2,
    armorProficiencies: ['Лёгкая', 'Средняя', 'Щит'], weaponProficiencies: ['Простое', 'Огнестрельное'],
    featuresByLevel: {
      1: ['Магические мануфактуры', 'Наложение заклинаний', 'Тинкер'],
      2: ['Волшебное ношение'],
      3: ['Архетип изобретателя', 'Инфузии'],
      4: ['Улучшение характеристики', 'Инструментrais忙碌'],
      5: ['Улучшение инфузий'],
      6: ['Улучшение характеристики', 'Эталонное оружие'],
      7: ['Архетип изобретателя (2)', 'Заговорыmiths экспериэнce'],
      8: ['Улучшение характеристики'],
      9: ['Инфузии (2)'],
      10: ['Улучшение характеристики', 'Архетип изобретателя (3)', 'Волшебное ношение (2)'],
      11: ['Инфузии (3)', 'Сохранение заклинаний'],
      12: ['Улучшение характеристики'],
      13: ['Архетип изобретателя (4)'],
      14: ['Улучшение характеристики', 'Магические мануфактуры (2)'],
      15: ['Улучшение инфузий (2)'],
      16: ['Улучшение характеристики'],
      17: ['Ротация инфузий'],
      18: ['Архетип изобретателя (5)'],
      19: ['Улучшение характеристики'],
      20: ['Душа искусства'],
    },
    spellcaster: 'half',
    spellSlots: [{ level: 1, used: 0, total: 2 }],
    subClasses: ['Алхимик', 'Артиллерист', 'Боевой кузнец', 'Хрономансер'],
  },
  warlock: {
    id: 'warlock', name: 'Колдун', description: 'Заклинатель, заключивший пакт с могущественным покровителем.',
    hitDie: 8, primaryStat: 'CHA',
    savingThrows: ['WIS', 'CHA'],
    skillPool: ['arcana', 'deception', 'history', 'intimidation', 'investigation', 'nature', 'religion'],
    skillChoices: 2,
    armorProficiencies: ['Лёгкая'], weaponProficiencies: ['Простое'],
    featuresByLevel: {
      1: ['Пакт с покровителем', 'Магический потенциал', 'Наложение заклинаний'],
      2: ['Призывы покровителя', 'Тайное натяжение'],
      3: ['Архетип покровителя', 'Дары pacts'],
      4: ['Улучшение характеристики'],
      5: ['Тайное натяжение (2)', 'Дары (2)'],
      6: ['Улучшение характеристики', 'Архетип покровителя (2)'],
      7: ['Тайное натяжение (3)', 'Дары (3)'],
      8: ['Улучшение характеристики'],
      9: ['Улучшение даров', 'Архетип покровителя (3)'],
      10: ['Улучшение характеристики', 'Дары (4)'],
      11: ['Колдовское натяжение', 'Архетип покровителя (4)'],
      12: ['Улучшение характеристики'],
      13: ['Дары (5)'],
      14: ['Улучшение характеристики', 'Архетип покровителя (5)'],
      15: ['Тайное натяжение (4)'],
      16: ['Улучшение характеристики'],
      17: ['Дары (6)', 'Архетип покровителя (6)'],
      18: ['Архетип покровителя (7)'],
      19: ['Улучшение характеристики'],
      20: ['Тайное натяжение (5)', 'Мастер-тайнознатец'],
    },
    spellcaster: 'full',
    spellSlots: [{ level: 1, used: 0, total: 1 }],
    subClasses: ['Архифея', 'Великий Древний', 'Дьявол', 'Бессмертный', 'Небесный покровитель', 'Мечforgeий', 'Покровитель Кроака'],
  },
  monk: {
    id: 'monk', name: 'Монах', description: 'Боевой мастер, использующий энергию ци для невероятных подвигов.',
    hitDie: 8, primaryStat: 'DEX',
    savingThrows: ['STR', 'DEX'],
    skillPool: ['acrobatics', 'athletics', 'history', 'insight', 'religion', 'stealth'],
    skillChoices: 2,
    armorProficiencies: [], weaponProficiencies: ['Простое', 'Короткие мечи'],
    featuresByLevel: {
      1: ['Защита без доспехов', 'Боевые искусства'],
      2: ['Увлечённость', 'Боевой стиль'],
      3: ['Путь монахосы', 'Дэдайс'],
      4: ['Улучшение характеристики', 'Замедление падения'],
      5: ['Дополнительная атака', 'Уверенный шаг'],
      6: ['Улучшение характеристики', 'Ци-фокус', 'Путь монахосы (2)'],
      7: ['Очищение тела', 'Небесное здоровье'],
      8: ['Улучшение характеристики'],
      9: ['Боевые искусства (2)', 'Непревзойдённое равновесие'],
      10: ['Улучшение характеристики', 'Пушистая чистота'],
      11: ['Ци-фокус (2)', 'Путь монахосы (3)'],
      12: ['Улучшение характеристики'],
      13: ['Очищение души'],
      14: ['Улучшение характеристики', 'Ци-фокус (3)'],
      15: ['Путь монахосы (4)'],
      16: ['Улучшение характеристики'],
      17: ['Ци-фокус (4)', 'Тело и дух'],
      18: ['Путь монахосы (5)'],
      19: ['Улучшение характеристики'],
      20: ['Совершенствование тела и духа'],
    },
    spellcaster: 'none',
    subClasses: ['Путь Открытой Ладони', 'Путь Стихий', 'Путь Тени', 'Путь Пьяного Учителя', 'Путь Солнечной Души', 'Путь Кисти Сользфора'],
  },
  paladin: {
    id: 'paladin', name: 'Паладин', description: 'Святой воин, связанный священной клятвой и божественной силой.',
    hitDie: 10, primaryStat: 'CHA',
    savingThrows: ['WIS', 'CHA'],
    skillPool: ['athletics', 'insight', 'intimidation', 'medicine', 'persuasion', 'religion'],
    skillChoices: 2,
    armorProficiencies: ['Лёгкая', 'Средняя', 'Тяжёлая', 'Щит'], weaponProficiencies: ['Простое', 'Военное'],
    featuresByLevel: {
      1: ['Божественное чувство', 'Наложение руки'],
      2: ['Боевой стиль', 'Наложение заклинаний', 'Божественная кара'],
      3: ['Божественное здоровье', 'Священная клятва'],
      4: ['Улучшение характеристики'],
      5: ['Дополнительная атака'],
      6: ['Улучшение характеристики', 'Аура защиты'],
      7: ['Священная клятва (2)'],
      8: ['Улучшение характеристики'],
      9: ['Аура храбрости'],
      10: ['Улучшение характеристики'],
      11: ['Улучшенная божественная кара'],
      12: ['Улучшение характеристики'],
      13: ['Аура защиты (2)'],
      14: ['Улучшение характеристики', 'Очищающий косар'],
      15: ['Аура храбрости (2)'],
      16: ['Улучшение характеристики'],
      17: ['Священная клятва (3)'],
      18: ['Аура защиты (3)'],
      19: ['Улучшение характеристики'],
      20: ['Святой покровитель'],
    },
    spellcaster: 'half',
    spellSlots: [{ level: 1, used: 0, total: 0 }],
    subClasses: ['Клятва Преданности', 'Клятва Древних', 'Клятва Мести', 'Клятва Короны', 'Клятва Славы', 'Клятва Часового', 'Клятва Клятвопреступника'],
  },
  ranger: {
    id: 'ranger', name: 'Следопыт', description: 'Охотник на чудовищ, защитник границы между цивилизацией и дикой природой.',
    hitDie: 10, primaryStat: 'DEX',
    savingThrows: ['STR', 'DEX'],
    skillPool: ['animal_handling', 'athletics', 'insight', 'investigation', 'nature', 'perception', 'stealth', 'survival'],
    skillChoices: 3,
    armorProficiencies: ['Лёгкая', 'Средняя', 'Щит'], weaponProficiencies: ['Простое', 'Военное'],
    featuresByLevel: {
      1: ['Враг на выбор', 'Избранный враг', 'Природный исследователь'],
      2: ['Наложение заклинаний', 'Боевой стиль'],
      3: ['Архетип следопыта', 'Главное оружие'],
      4: ['Улучшение характеристики'],
      5: ['Дополнительная атака'],
      6: ['Улучшение характеристики', 'Природный исследователь (2)', 'Избранный враг (2)'],
      7: ['Земная хватка'],
      8: ['Улучшение характеристики', 'Земное движение'],
      9: ['Главное оружие (2)'],
      10: ['Улучшение характеристики', 'Природный исследователь (3)'],
      11: ['Скорость ветра'],
      12: ['Улучшение характеристики'],
      13: ['Избранный враг (3)', 'Природный исследователь (4)'],
      14: ['Улучшение характеристики', 'Земное уклонение'],
      15: ['Главное оружие (3)'],
      16: ['Улучшение характеристики'],
      17: ['Архетип следопыта (2)'],
      18: ['Незаметные чувства'],
      19: ['Улучшение характеристики'],
      20: ['Охотник-убийца'],
    },
    spellcaster: 'half',
    spellSlots: [{ level: 1, used: 0, total: 0 }],
    subClasses: ['Охотник', 'Звериный укротитель', 'Глубинный следопыт', 'Саамтиий следопыт', 'Сумрачный охотник', 'Следопыт военаражени'],
  },
  sorcerer: {
    id: 'sorcerer', name: 'Чародей', description: 'Заклинатель с врождённой магией, текущей в крови.',
    hitDie: 6, primaryStat: 'CHA',
    savingThrows: ['CON', 'CHA'],
    skillPool: ['arcana', 'deception', 'insight', 'intimidation', 'persuasion', 'religion'],
    skillChoices: 2,
    armorProficiencies: [], weaponProficiencies: ['Кинжалы', 'Дартс', 'Праща', 'Боевые посохи', 'Лёгкие арбалеты'],
    featuresByLevel: {
      1: ['Наложение заклинаний', 'Происхождение чародея'],
      2: ['Источник магии', 'Гибкое заклинание'],
      3: ['Метамагия', 'Происхождение чародея (2)'],
      4: ['Улучшение характеристики'],
      5: ['Метамагия (2)'],
      6: ['Улучшение характеристики', 'Происхождение чародея (3)'],
      7: ['Метамагия (3)'],
      8: ['Улучшение характеристики'],
      9: ['Происхождение чародея (4)'],
      10: ['Улучшение характеристики', 'Метамагия (4)'],
      11: ['Врождённая магия'],
      12: ['Улучшение характеристики'],
      13: ['Происхождение чародея (5)'],
      14: ['Улучшение характеристики', 'Метамагия (5)'],
      15: ['Происхождение чародея (6)'],
      16: ['Улучшение характеристики'],
      17: ['Метамагия (6)'],
      18: ['Происхождение чародея (7)'],
      19: ['Улучшение характеристики'],
      20: ['Душа чародея'],
    },
    spellcaster: 'full',
    spellSlots: [{ level: 1, used: 0, total: 2 }],
    subClasses: ['Происхождение Дракона', 'Происхождение Дикой Магии', 'Происхождение Бури', 'Происхождение Теней', 'Происхождение Изначальной Силы', 'Происхождение Часов', 'Происхождение Абберранта'],
  },
};

export const RACES: Record<string, Race> = {
  human: {
    id: 'human', name: 'Человек',
    description: 'Универсальная раса, адаптивная и амбициозная.',
    abilityBonuses: { STR: 1, DEX: 1, CON: 1, INT: 1, WIS: 1, CHA: 1 },
    speed: 30, size: 'Medium',
    languages: ['Общий'],
    traits: ['+1 ко всем характеристикам', 'Дополнительный язык'],
  },
  elf: {
    id: 'elf', name: 'Эльф',
    description: 'Грациозные существа с древней магией.',
    abilityBonuses: { DEX: 2, INT: 1 },
    speed: 30, size: 'Medium',
    languages: ['Общий', 'Эльфийский'],
    traits: ['Тёмное зрение 60ft', 'Наследие фей', 'Транс'],
    subRaces: [
      { id: 'high_elf', name: 'Высший эльф', abilityBonuses: { INT: 1 }, traits: ['+1 ИНТ'] },
      { id: 'wood_elf', name: 'Лесной эльф', abilityBonuses: { WIS: 1 }, traits: ['+1 МУД', 'Маскировка в лесу'] },
    ],
  },
  dwarf: {
    id: 'dwarf', name: 'Дварф',
    description: 'Стойкие подземные жители, мастера ремесла.',
    abilityBonuses: { CON: 2, WIS: 1 },
    speed: 25, size: 'Medium',
    languages: ['Общий', 'Дварфийский'],
    traits: ['Тёмное зрение 60ft', 'Дварфийская стойкость'],
    subRaces: [
      { id: 'hill_dwarf', name: 'Холмовой дварф', abilityBonuses: { WIS: 1 }, traits: ['Дварфийская выносливость'] },
    ],
  },
  halfling: {
    id: 'halfling', name: 'Халфлинг',
    description: 'Маленькие, удачливые и ловкие.',
    abilityBonuses: { DEX: 2, CHA: 1 },
    speed: 25, size: 'Small',
    languages: ['Общий', 'Халфлингийский'],
    traits: ['Удачливость', 'Храбрость'],
  },
  aasimar: {
    id: 'aasimar', name: 'Асимар',
    description: 'Потомок небесных существ, наделённый светом и добротой.',
    abilityBonuses: { CHA: 2 },
    speed: 30, size: 'Medium',
    languages: ['Общий', 'Небесный'],
    traits: ['Тёмное зрение 60ft', 'Небесное сопротивление', 'Лечащие руки'],
  },
  verdan: {
    id: 'verdan', name: 'Вердан',
    description: 'Кочевая раса гоблиноидов, стремящаяся к росту и знаниям.',
    abilityBonuses: { CHA: 2, CON: 1 },
    speed: 30, size: 'Small',
    languages: ['Общий', 'Гоблинский'],
    traits: ['Телепатия 30ft', 'Счастливая случайность', 'Адаптивность'],
  },
  changeling: {
    id: 'changeling', name: 'Изменяющий',
    description: 'Метаморф, способный менять облик по желанию.',
    abilityBonuses: { CHA: 2, INT: 1 },
    speed: 30, size: 'Medium',
    languages: ['Общий'],
    traits: ['Изменение облика', 'Сопротивление очарованию', 'Телепатия'],
  },
  satyr: {
    id: 'satyr', name: 'Сатир',
    description: 'Рогатый фей-кочевник, любящий музыку, вино и веселье.',
    abilityBonuses: { CHA: 2, DEX: 1 },
    speed: 35, size: 'Medium',
    languages: ['Общий', 'Сильванский'],
    traits: ['Магическое сопротивление', 'Бодрящий рог', 'Чтение мыслей'],
  },
  half_elf: {
    id: 'half_elf', name: 'Полуэльф',
    description: 'Потомок человека и эльфа, сочетающий черты обеих рас.',
    abilityBonuses: { CHA: 2 },
    speed: 30, size: 'Medium',
    languages: ['Общий', 'Эльфийский'],
    traits: ['Тёмное зрение 60ft', 'Наследие фей', 'Универсальность навыков'],
  },
  dragonborn: {
    id: 'dragonborn', name: 'Драконорождённый',
    description: 'Потомок драконов, наделённый стихийным дыханием и чешуёй.',
    abilityBonuses: { STR: 2, CHA: 1 },
    speed: 30, size: 'Medium',
    languages: ['Общий', 'Драконий'],
    traits: ['Драконье дыхание', 'Сопротивление урону', 'Драконье происхождение'],
  },
};

export const ALIGNMENTS = [
  'Законно-добрый', 'Нейтрально-добрый', 'Хаотично-добрый',
  'Законно-нейтральный', 'Нейтральный', 'Хаотично-нейтральный',
  'Законно-злой', 'Нейтрально-злой', 'Хаотично-злой',
];

export const BACKGROUNDS: Background[] = [
  {
    id: 'soldier',
    name: 'Солдат',
    description: 'Военная карьера: тренировки, сражения, командование. Знаешь дисциплину и оружие.',
    skillProficiencies: ['athletics', 'intimidation'],
    items: [
      { name: 'Кольчуга', quantity: 1 },
      { name: 'Кинжал', quantity: 1 },
      { name: 'Трофей павшего врага', quantity: 1 },
      { name: 'Комплект игральных костей', quantity: 1 },
      { name: 'Набор для костра', quantity: 1 },
    ],
    coins: { gp: 10 },
    feature: 'Воинское звание',
  },
  {
    id: 'sage',
    name: 'Мудрец',
    description: 'Годы учёбы в библиотеках и архивах. Знание древних тайн и книг.',
    skillProficiencies: ['arcana', 'history'],
    items: [
      { name: 'Бутылка чернил', quantity: 1 },
      { name: 'Перо', quantity: 1 },
      { name: 'Нож', quantity: 1 },
      { name: 'Письмо от умершего коллеги', quantity: 1 },
      { name: 'Лист пергамента', quantity: 1 },
      { name: 'Книга в кожаном переплёте', quantity: 1 },
    ],
    coins: { gp: 5 },
    feature: 'Изыскатель',
  },
  {
    id: 'noble',
    name: 'Дворянин',
    description: 'Вы из благородной семьи, рождённый в роскоши и обученный манерам.',
    skillProficiencies: ['history', 'persuasion'],
    items: [
      { name: 'Тонкая одежда', quantity: 1 },
      { name: 'Перстень-печать', quantity: 1 },
      { name: 'Свиток родословной', quantity: 1 },
      { name: 'Кожаный пояс с кошельком', quantity: 1 },
      { name: 'Кинжал', quantity: 1 },
      { name: 'Комплект игральных костей', quantity: 1 },
    ],
    coins: { gp: 25 },
    feature: 'Положение в обществе',
  },
  {
    id: 'criminal',
    name: 'Преступник',
    description: 'Тёмное прошлое: воровство, контрабанда, теневые сделки.',
    skillProficiencies: ['deception', 'stealth'],
    items: [
      { name: 'Ломик', quantity: 1 },
      { name: 'Тёмная одежда с капюшоном', quantity: 1 },
      { name: 'Мешочек с шариками', quantity: 1 },
      { name: 'Комплект игральных костей', quantity: 1 },
      { name: 'Кусок трубы', quantity: 1 },
      { name: 'Кинжал', quantity: 1 },
    ],
    coins: { gp: 15 },
    feature: 'Криминальный контакт',
  },
  {
    id: 'hermit',
    name: 'Отшельник',
    description: 'Жизнь вдали от людей, в поисках духовной или научной истины.',
    skillProficiencies: ['medicine', 'religion'],
    items: [
      { name: 'case с иглами и нитками', quantity: 1 },
      { name: 'Комплект для костра', quantity: 1 },
      { name: 'Годовой запас собранных трав', quantity: 1 },
      { name: 'Благовония', quantity: 1 },
      { name: 'Книга в кожаном переплёте', quantity: 1 },
    ],
    coins: { gp: 5 },
    feature: 'Открытие',
  },
  {
    id: 'folk_hero',
    name: 'Народный герой',
    description: 'Из простого люда, защитник угнетённых и борец за справедливость.',
    skillProficiencies: ['animal_handling', 'survival'],
    items: [
      { name: 'Крестьянская одежда', quantity: 1 },
      { name: 'Деревянный щит', quantity: 1 },
      { name: 'Железный котелок', quantity: 1 },
      { name: 'Вертающаяся лопата', quantity: 1 },
      { name: 'Комплект для костра', quantity: 1 },
    ],
    coins: { gp: 10 },
    feature: 'Деревенская известность',
  },
  {
    id: 'acolyte',
    name: 'Служитель культа',
    description: 'Служба в храме, знание ритуалов и духовных текстов.',
    skillProficiencies: ['insight', 'religion'],
    items: [
      { name: 'Священный символ', quantity: 1 },
      { name: 'Молитвенник', quantity: 1 },
      { name: 'Пять палочек благовоний', quantity: 1 },
      { name: 'Одежда служителя', quantity: 1 },
      { name: 'Одежные сандалии', quantity: 1 },
    ],
    coins: { gp: 15 },
    feature: 'Убежище приверженца',
  },
];

export const SKILLS_LIST: SkillInfo[] = [
  { id: 'acrobatics', name: 'Акробатика', stat: 'DEX', description: 'Прыжки, кувырки, балансирование и акробатические трюки. Используется для уклонения, удержания равновесия и снижения урона при падении.' },
  { id: 'animal_handling', name: 'Уход за животными', stat: 'WIS', description: 'Понимание поведения животных, приручение, успокоение и верховая езда. Помогает контролировать ездовое животное в бою.' },
  { id: 'arcana', name: 'Магия', stat: 'INT', description: 'Знание тайной магии, заклинаний, магических существ, символов и ритуалов. Используется для распознавания магических эффектов.' },
  { id: 'athletics', name: 'Атлетика', stat: 'STR', description: 'Физические усилия: лазание, плавание, прыжки и преодоление препятствий. Используется для захвата и толчка в бою.' },
  { id: 'deception', name: 'Обман', stat: 'CHA', description: 'Лгать, вводить в заблуждение, блефовать и скрывать правду. Применяется для сокрытия намерений или убеждения в неправде.' },
  { id: 'history', name: 'История', stat: 'INT', description: 'Знание исторических событий, династий, войн и легенд. Применяется для распознавания древних артефактов и традиций.' },
  { id: 'insight', name: 'Проницательность', stat: 'WIS', description: 'Чтение чужих эмоций, намерений и лжи. Используется для определения вранья и понимания скрытых мотивов.' },
  { id: 'intimidation', name: 'Запугивание', stat: 'CHA', description: 'Устрашение силой, угрозами или присутствием. Применяется, чтобы заставить кого-то подчиниться из страха.' },
  { id: 'investigation', name: 'Расследование', stat: 'INT', description: 'Поиск подсказок, логические выводы, анализ места преступления. Используется для поиска скрытых дверей и ловушек.' },
  { id: 'medicine', name: 'Медицина', stat: 'WIS', description: 'Стабилизация умирающих, диагностика болезней, первая помощь и уход за ранами. Определяет успешность лечения.' },
  { id: 'nature', name: 'Природа', stat: 'INT', description: 'Знание флоры, фауны, погоды, местности и естественных циклов. Помогает ориентироваться и определять опасности природы.' },
  { id: 'perception', name: 'Восприятие', stat: 'WIS', description: 'Заметить скрытое, услышать тихое, почувствовать опасность. Используется для определения инициативы и засады.' },
  { id: 'performance', name: 'Выступление', stat: 'CHA', description: 'Танец, пение, игра на инструментах и ораторское искусство. Применяется для заработка и привлечения внимания.' },
  { id: 'persuasion', name: 'Убеждение', stat: 'CHA', description: 'Дипломатия, влияние через аргументы и обаяние. Помогает дружить с NPC и получать помощь без угроз.' },
  { id: 'religion', name: 'Религия', stat: 'INT', description: 'Знание богов, культов, ритуалов и священных текстов. Используется для распознавания божественной магии и undead.' },
  { id: 'sleight_of_hand', name: 'Ловкость рук', stat: 'DEX', description: 'Карманная кража, фокусы, прятанье предметов на себе. Применяется для незаметных манипуляций.' },
  { id: 'stealth', name: 'Скрытность', stat: 'DEX', description: 'Скрытое передвижение, маскировка, тихое приближение. Используется, чтобы остаться незамеченным.' },
  { id: 'survival', name: 'Выживание', stat: 'WIS', description: 'Ориентирование, слежение за добычей, поиск еды/воды, предсказание погоды. Критично в дикой местности.' },
];

export const WIZARD_STEPS = ['Раса', 'Класс', 'Характеристики', 'Навыки', 'Детали', 'Обзор'];

export const STAT_METHODS = [
  { value: '4d6', label: '4d6 бросок' },
  { value: 'standard', label: 'Стандартный массив' },
];

export const STANDARD_ARRAY = { STR: 15, DEX: 14, CON: 13, INT: 12, WIS: 10, CHA: 8 };

export const LIBRARY_CHARACTERS: Character[] = [
  {
    id: 'lib_warrior', name: 'Гром Железный', race: 'dwarf', class: 'fighter', level: 1,
    background: 'Солдат', alignment: 'Законно-добрый',
    stats: { STR: 16, DEX: 12, CON: 14, INT: 10, WIS: 12, CHA: 8 },
    baseStats: { STR: 14, DEX: 12, CON: 12, INT: 10, WIS: 12, CHA: 8 },
    racialBonus: { STR: 2, CON: 2 },
    skills: [
      { skillId: 'athletics', proficient: true, expertise: false },
      { skillId: 'intimidation', proficient: true, expertise: false },
    ],
    savingThrows: { STR: true, CON: true },
    hitPoints: 12, maxHitPoints: 12, armorClass: 16, armorId: 'chain_mail', hasShield: true, proficiencyBonus: 2, speed: 25,
    languages: ['Общий', 'Дварфийский'], features: ['Второе дыхание', 'Боевой стиль'],
    inventory: [{ id: 'i1', name: 'Длинный меч', quantity: 1, equipped: true }],
    coins: { pp: 0, gp: 25, sp: 0, cp: 0 },
    experiencePoints: 0, backstory: 'Бывший солдат наёмной дружины.', characterSheet: '',
    createdAt: 0, updatedAt: 0, isLibrary: true,
  },
  {
    id: 'lib_wizard', name: 'Лирель Звёздная', race: 'elf', class: 'wizard', level: 1,
    background: 'Учёный', alignment: 'Нейтрально-добрый',
    stats: { STR: 8, DEX: 14, CON: 12, INT: 16, WIS: 12, CHA: 10 },
    baseStats: { STR: 8, DEX: 14, CON: 12, INT: 16, WIS: 12, CHA: 10 },
    racialBonus: { DEX: 2 },
    skills: [
      { skillId: 'arcana', proficient: true, expertise: false },
      { skillId: 'history', proficient: true, expertise: false },
    ],
    savingThrows: { INT: true, WIS: true },
    hitPoints: 8, maxHitPoints: 8, armorClass: 12, armorId: 'none', hasShield: false, proficiencyBonus: 2, speed: 30,
    languages: ['Общий', 'Эльфийский'], features: ['Арканное восстановление', 'Заклинания'],
    inventory: [{ id: 'i2', name: 'Посох', quantity: 1, equipped: true }],
    coins: { pp: 0, gp: 15, sp: 0, cp: 0 },
    experiencePoints: 0, backstory: 'Молодая волшебница из Академии.', characterSheet: '',
    createdAt: 0, updatedAt: 0, isLibrary: true,
  },
  {
    id: 'lib_rogue', name: 'Шэдоу', race: 'halfling', class: 'rogue', level: 1,
    background: 'Преступник', alignment: 'Хаотично-нейтральный',
    stats: { STR: 10, DEX: 17, CON: 12, INT: 14, WIS: 10, CHA: 8 },
    baseStats: { STR: 10, DEX: 17, CON: 12, INT: 14, WIS: 10, CHA: 8 },
    racialBonus: { DEX: 2 },
    skills: [
      { skillId: 'sleight_of_hand', proficient: true, expertise: false },
      { skillId: 'stealth', proficient: true, expertise: false },
      { skillId: 'deception', proficient: true, expertise: false },
    ],
    savingThrows: { DEX: true, INT: true },
    hitPoints: 9, maxHitPoints: 9, armorClass: 14, armorId: 'leather', hasShield: false, proficiencyBonus: 2, speed: 25,
    languages: ['Общий', 'Халфлингийский'], features: ['Скрытая атака', 'Воровской жаргон'],
    inventory: [{ id: 'i3', name: 'Короткий лук', quantity: 1, equipped: true }],
    coins: { pp: 0, gp: 30, sp: 0, cp: 0 },
    experiencePoints: 0, backstory: 'Бывший шулер из портового города.', characterSheet: '',
    createdAt: 0, updatedAt: 0, isLibrary: true,
  },
  {
    id: 'lib_cleric', name: 'Брат Алдрик', race: 'human', class: 'cleric', level: 1,
    background: 'Жрец', alignment: 'Законно-добрый',
    stats: { STR: 12, DEX: 8, CON: 14, INT: 10, WIS: 16, CHA: 12 },
    baseStats: { STR: 12, DEX: 8, CON: 14, INT: 10, WIS: 16, CHA: 12 },
    racialBonus: { STR: 1, DEX: 1, CON: 1, INT: 1, WIS: 1, CHA: 1 },
    skills: [
      { skillId: 'medicine', proficient: true, expertise: false },
      { skillId: 'religion', proficient: true, expertise: false },
    ],
    savingThrows: { WIS: true, CHA: true },
    hitPoints: 10, maxHitPoints: 10, armorClass: 16, armorId: 'chain_mail', hasShield: true, proficiencyBonus: 2, speed: 30,
    languages: ['Общий', 'Эльфийский'], features: ['Божественная воля', 'Изгнание нежити'],
    inventory: [{ id: 'i4', name: 'Кольчуга', quantity: 1, equipped: true }],
    coins: { pp: 1, gp: 10, sp: 0, cp: 0 },
    experiencePoints: 0, backstory: 'Послушник храма Солнца.', characterSheet: '',
    createdAt: 0, updatedAt: 0, isLibrary: true,
  },
];
